apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: adarsh893/book-my-movie-auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@auth-postgres-cluster-ip-srv:5432/auth
            - name: CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BROKERS
              value: bookmymovie-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_GROUP_ID
              value: auth-group
            - name: SERVICE_NAME
              value: auth-service


## cluster ip service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-ip-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth-port
      protocol: TCP
      port: 3000
      targetPort: 3000
