apiVersion: skaffold/v4beta3
kind: Config
manifests:
  kustomize:
    paths:
      - infra/app
build:
  local:
    push: false
  artifacts:
    - image: adarsh893/book-my-movie-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: adarsh893/book-my-movie-movie
      context: movie
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: adarsh893/book-my-movie-theater
      context: theater
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: adarsh893/book-my-movie-show
      context: show
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
