apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie-container
          image: adarsh893/book-my-movie-movie
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@movie-postgres-cluster-ip-srv:5432/movie


## cluster ip service
---
apiVersion: v1
kind: Service
metadata:
  name: movie-cluster-ip-srv
spec:
  selector:
    app: movie
  ports:
    - name: movie-port
      protocol: TCP
      port: 3001
      targetPort: 3001
