export enum Permission {
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  THEATER_CREATE = "THEATER_CREATE",
  THEATER_UPDATE = "THEATER_UPDATE",
  THEATER_DELETE = "THEATER_DELETE",

  SHOW_CREATE = "SHOW_CREATE",
  SHOW_UPDATE = "SHOW_UPDATE",
  SHOW_DELETE = "SHOW_DELETE",

  BOOKING_CREATE = "BOOKING_CREATE",
  BOOKING_CANCEL = "BOOKING_CANCEL",
}
