export enum Permission {
  // User
  // No create as signup is public
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  // Movie
  MOVIE_CREATE = "MOVIE_CREATE",
  MOVIE_READ = "MOVIE_READ",
  MOVIE_UPDATE = "MOVIE_UPDATE",
  MOVIE_DELETE = "MOVIE_DELETE",

  // Theater
  THEATER_CREATE = "THEATER_CREATE",
  THEATER_READ = "THEATER_READ",
  THEATER_UPDATE = "THEATER_UPDATE",
  THEATER_DELETE = "THEATER_DELETE",

  // Show
  SHOW_CREATE = "SHOW_CREATE",
  SHOW_READ = "SHOW_READ",
  SHOW_UPDATE = "SHOW_UPDATE",
  SHOW_DELETE = "SHOW_DELETE",

  // Booking
  BOOKING_CREATE = "BOOKING_CREATE",
  BOOKING_READ = "BOOKING_READ",
  BOOKING_CANCEL = "BOOKING_CANCEL",

  // Payment
  PAYMENT_READ = "PAYMENT_READ",
  PAYMENT_REFUND = "PAYMENT_REFUND",
}
