apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic

metadata:
  name: show-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: bookmymovie

spec:
  config:
    retention.ms: 604800000
    cleanup.policy: delete
