apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic

metadata:
  name: movie-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: bookmymovie

spec:
  topicName: movie-topic
  partitions: 2

  replicas: 1

  config:
    cleanup.policy: delete

    retention.ms: 604800000

    compression.type: producer

    min.insync.replicas: 1

---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: movie-topic-dlt
  namespace: kafka
  labels:
    strimzi.io/cluster: bookmymovie

spec:
  topicName: movie-topic-dlt
  partitions: 2
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 2592000000 # 30 days
